name: Unit Tests

on:
  - push
  - workflow_dispatch
  
permissions:
  contents: read

jobs:
  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup BATS
      uses: mig4/setup-bats@af9a00deb21b5d795cabfeaa8d9060410377686d # v1

    - name: checkout
      uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

    - name: unit tests
      run: bats $GITHUB_WORKSPACE/operations/_scripts/deploy/tests/.
